#Sources 
:sources: 
  Product: 
    :poll_interval: 300
    :queue: product
    :priority: 1
    :partition_type: app
  Customer: 
    :poll_interval: 300
    :queue: customer
    :priority: 5
    :partition_type: app
 
:test: 
  :bulk_sync_poll_interval: 3600
  :licensefile: settings/license.key
  :syncserver: http://localhost:9292/application/
  :redis: localhost:6379
:production: 
  :bulk_sync_poll_interval: 3600
  :licensefile: settings/license.key
  :syncserver: http://localhost:9292/application/
  :redis: localhost:6379
:development: 
  :bulk_sync_poll_interval: 3600
  :licensefile: settings/license.key
  :syncserver: http://localhost:9292/application/
  :bulk_sync_poll_interval: 3600
  :blackberry_bulk_sync: true